### ISSUE TITLE
Email-Notification for each shared file in album

### ISSUE THREAD

**Issue by Electrotec81** [nkming2/nc-photos#2]
First: I've purchased this app and i love it.
Thanks for this awesome work.

But, if someone put files in a shared album, i recieve a email-notification for every file.
I can't find parameters in nextcloud or in the app to change this.
Is this a bug?

**Comment by nkming2** [comment]
Hi, glad that you like the app. :wink: 

When someone add a photo to a shared album, the app will create a new share for that photo with everyone in the shared album. Please check your server's Notification settings.

**Comment by Electrotec81** [comment]
I checked all the settings and couldn't find anything that would prevent it. Do you have a tip for me?

**Comment by nkming2** [comment]
Hi, you can try unchecking the options in Settings -> Notifications.

![Screenshot](https://user-images.githubusercontent.com/6094832/198043846-3dd689b1-8737-4264-9e19-bb6fbd3cdaa2.png)

**Comment by Electrotec81** [comment]
I have switched off the email notification completely. Under "Personal" and "Administration" -> "Activities". The problem still exists. When an album is shared with me by a user, I get an email for every picture in it. Do you have any other ideas what this could be?

![Screenshot_20221102-220352_FairEmail](https://user-images.githubusercontent.com/116487945/199604552-b5b20a56-2d99-41e2-abd4-b82174ba7dcf.jpg)

![Screenshot_20221102-220919_Vivaldi Browser](https://user-images.githubusercontent.com/116487945/199604594-ca5bc522-bf84-458c-9612-714a68b587e2.jpg)

![Screenshot_20221102-221024_Vivaldi Browser](https://user-images.githubusercontent.com/116487945/199604652-44649b70-0bdf-4e36-8fad-9d013387fa26.jpg)

![Screenshot_20221102-221038_Vivaldi Browser](https://user-images.githubusercontent.com/116487945/199604688-a8f84efb-8d8c-4253-bf08-6ee9300fb9e9.jpg)

**Comment by nkming2** [comment]
That's weird. Is this running a vanilla Nextcloud server (downloaded from nextcloud.com or using the official docker image) or some fork of it?

**Comment by Electrotec81** [comment]
Its a Nextcloudpi-Image. Freshly installed about 14 days ago.

NextCloudPi version: v1.50.3
NextCloudPi image: NextCloudPi_RaspberryPi_v1.50.3.img
OS : Debian GNU/Linux 11. 5.15.74-v8+ (aarch64)
Nextcloud Version: 24.0.5.1

It doesn't matter.
We don't necessarily need shared albums. The app is still amazing.
Just thought it would be interesting to know if it's a parameter in my configuration.
As soon as I have some time, I will test different settings again and report back the result.

**Comment by nkming2** [comment]
Hi, the GitHub repo acts only as a mirror and I rarely monitor it, as such I'm closing all issues and disabling the issue tracker here, if you have further questions please head to the GitLab repo instead (https://gitlab.com/nkming2/nc-photos), sorry for your inconvenience!
